# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter blog post title.', max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, help_text='Enter blog post slug.', max_length=250, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text="Enter blog post description which doesn't contain HTML tags", verbose_name='Description')),
                ('content', models.TextField(help_text='Enter blog post content.', verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PostAllTextField',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('blog.post',),
        ),
    ]
